---
title: "Style radzenia sobie ze stresem oraz bólem a powrót do sportu po przebytej kontuzji u osób trenujących sztuki lub sporty walki"

output:
  revealjs::revealjs_presentation:
    self_contained: false
    lib_dir: reveal_libs
    theme: moon
    center: true
    incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Cel i tło badań

## Cel

Celem badań jest uzyskanie informacji na temat tego, czy preferowany sposób radzenia sobie ze stresem oraz stosowanie danej strategii radzenia sobie z bólem i przekonania na temat umiejscowienia kontroli bólu wpływają na to, czy osoby trenujące sztuki lub sporty walki, po przebytej kontuzji, wracają do regularnych treningów.

## Tło badań

*	Emocjonalna odpowiedź na doznaną kontuzję stanowi ważny aspekt rehabilitacji i często stanowi o jej wyniku _(Quackenbush & Crossman, 1994)_
* Urazy u osób trenujących regularnie najczęściej wywołują negatywne emocje i są sytuacjami stresowymi _(Clement & Shannon, 2011)_
*	Rehabilitacja, wsparcie społeczne i psychologiczna pomóc dla osób, które doznały wypadku przynosi lepsze efekty jeśli dopasowana jest do psychologicznych predyspozycji osoby poszkodowanej _(Fisher, Mullins, & Frye, 1993)_


## Tło badań

*	Sporty i sztuki walki charakteryzują się dość wysoką urazowością (szczególnie boks i zapasy) związane jest to między innymi z urazami w bezpośrednich walkach sportowych (Bujak, 2008)
*	Dominującymi urazami są urazy średnie i lekkie (rozciągnięcia więzadeł i stłuczenia) – co oznacza, że po okresie rehabilitacji osoby, które doznały kontuzji mogą zwykle wrócić do regularnych treningów (Bujak, 2008)
* Im większy poziom zaawansowania zawodnika, tym mniejsze występuje ryzyko kontuzji (Şentun, 2012)
*	Osoby trenujące sztuki walki wyróżniają się na tle innych sportowców różnymi aspektami psychologicznymi np. samooceną (Janowska, Wojdat, Antkowiak, & Stępniak, 2016)

 
## Strategie radzenia sobie ze stresem (wg. Kwestionariusza CISS)

*  styl skoncentrowany na zadaniu (SSZ)
*  styl skoncentrowany na emocjach (SSE)
*  styl skoncentrowany na unikaniu (SSU)
    +  angażowanie się w czynności zastępcze (AKC) 
    +  poszukiwanie kontaktów towarzyskich (PKT)

## Style radzenia sobie z bólem (wg skal kwestionariusza CSQ)

* Przewartościowanie doznań
* Katastrofizowanie
* Ignorowanie doznań
* Modlenie się
* pokładanie nadziei
* Deklarowanie radzenia sobie
* Zwiększona aktywność behawioralna


## Umiejscowienie kontroli bólu (wg Kwestionariusza BPCQ)

* wewnętrzne
* wpływ personelu medycznego
* zdarzenia przypadkowe



## HIPOTEZY

* W grupie osób, które powróciły do sportu po przebytej kontuzji znajdzie się więcej osób o **zadaniowym stylu radzenia sobie ze stresem** niż osób o **emocjonalnym** oraz **unikowym stylu radzenia sobie ze stresem.**
* W grupie osób, które powróciły do sportu po przebytej kontuzji znajdzie się więcej osób, które preferują styl polegający na **deklarowaniu radzenia sobie oraz zwiększonej aktywności behawioralnej** niż w grupie osób, które nie powróciły do sportu.

## HIPOTEZY

* Ilość osób powracających do sportu po kontuzji, będzie malała wraz ze wzrostem długości przerwy w trenowaniu spowodowanej kontuzją i rehabilitacją, niezależnie od stylu radzenia sobie ze stresem i bólem.
* W grupie osób, które powróciły do sportu po przebytej kontuzji znajdzie się więcej osób, które przypisują kontrolę bólu **czynnikom wewnętrznym (osobistym)** niż osób, które przypisują kontrolę bólu **wpływom lekarzy** oraz **przypadkowym zdarzeniom**


# MATERIAŁ I METODY

## Osoby badane

* 120 mężczyzn i kobiet, trenujących regularnie (przynajmniej 2 lata przed wystąpieniem kontuzji) sporty lub sztuki walki
* Rekrutowane będą osoby należące do Akademickiego Związku Sportowego różnych uczelni, z poszczególnych sekcji (judo, karate, aikido, Ju-jitsu, MMA, boks, kickboxing)
* Osoby, które nie mogą kontynuować treningów ze względów zdrowotnych (przebyta kontuzja uniemożliwa powrót) nie są brane pod uwagę
* Osoby badane nie muszą doznać kontuzji podczas treningu danego sportu, jednak musi oni uniemożliwać regularne treningi na okres przynajmniej 3 miesięcy 

## Ankieta 

* Dane demograficzne
* Rodzaj trenowanych sztuk/sportów walki
* Długość rehabilitacji
* Rodzaju doznanej kontuzji
* Pytanie dotyczące powrotu bądź nie do regularnych treningów

## Kwestionariusze

* CISS - Kwestionariusz Radzenia Sobie w Sytuacjach Stresowych
* CSQ - Kwestionariusz Strategii Radzenia Sobie z Bólem
* BPCQ - Kwestionariusz Przekonań na Temat Kontroli Bólu


## Statystyka

* Osoby badane zostaną podzielone na 2 grupy ze względu na powrót lub brak powrotu do regularnych treningów
* Wieloczynnikowa ANOVA - zmienna grupująca powrót lub jego brak, czynniki to poszczególnie strategie/style/umiejescowienie kontroli + długość rehabilitacji
* Pozwala to na stwierdzenie, czy dane grupy różną się pod względem preferowanych stylów i strategii
* Dodatkową zmienną, według której można dokonać podziału wewnątrzgrupowego to zmienna płci 

# Bibliografia

##Bibliografia

* Bujak, Z. (2008). Incidence of injuries in martial arts with taekwon-do as an example. Movement for Culture, 8, 118–132. 

* Clement, D., & Shannon, V. R. (2011). Injured Athletes’ Perceptions About Social Support. Journal of Sport Rehabilitation, 20, 457–470. https://doi.org/10.1123/jsr.20.4.457

* Fisher, A. C., Mullins, S. A., & Frye, P. A. (n.d.). Athletic Trainers Attitudes and Judgments of Injured Athletes Rehabilitation Adherence, 2, 43–47.

## Bibliografia

* Janowska, P., Wojdat, M., Antkowiak, M., & Stępniak, R. (2016). Self-assessment and selected elements of the social position of judokas. Journal of Education, Health and Sport, 6(9), 664–673.

* Quackenbush, N., & Crossman, J. (1994). Injured Athletes: A Study of Emotional Responses. Journal of Sport Behavior, 3(17).

* Şentun, B. (2012). Examination of a ikido and Injury – Own Reflections. Journal of Martial Arts Anthropology, 12(2), 70–72.


# Dziękuję za uwagę

## Agata Zywert 
Gdański Uniwersytet Medyczny

psychologia zdrowia 

II rok

2018

