---
title: "Neuroobrazowanie"
author: "Agata Zywert"
date: "22 marca 2018"
output: html_document
---

### **Czynnościowa diagnostyka obrazowa w neuropsychologii**

            by prof. dr hab. med. Piotr Lass 
    
  `tam na początku to są raczej tylko ciekawostki i żarciki, więc przejdę już do konkretów bardziej`
  
#### _**Podstawy podstaw podstaw**_

##### **Trzy (cztery) modele chorobowości/umieralności:**
* stara Europa/Trzeci Świat – choroby zakaźne
* okres szybkiej industrializacji – choroby serca
* okres postindustrialny 
    + choroby serca: poniżej 50%
     + nowotwory: 20 – 30% 
    + urazy: ok. 5 % 
     + schorzenia psychoneurologiczne ok. 15%  (!), a ileż wesołych przygód Huffa i Puffa po drodze – to Wasza Specjalność, Mesdames e Messieurs!
  + reszta – ok. 10% 
* model WNP `nie wiem co to ` jako specyfika

##### **Podstawy podstaw ciąg dalszy**

* Neuropsychologia i neuropsychiatria nie dorobiły się bazy diagnostyki laboratoryjnej – jeszcze - nie można rozpoznać tych dysfunkcji badaniem krwi lub moczu, jednym z nielicznych wyjątków jest oznaczanie amyloidu w płynie mózgowo-rdzeniowym w ch. Alzheimera, ale jest postęp!.  
* Na dziś wszelako`(m) heee` więc podstawą diagnostyki są więc badania psychologiczne ++  oraz diagnostyka obrazowa.  
* Czynność mózgu jest stanem elektrycznym. Niedoskonałym zapisem tej czynności jest EEG. W związku z tym: 
* Tworząc obraz („mapę”) czynności mózgu posługujemy się parametrami pośrednimi – czynności poszczególnych jego okolic przez uzyskanie obrazów regionalnego mózgowego przepływu krwi i  regionalnego metabolizmu glukozy.  

##### **Dalej**

* Wzrostowi aktywności poszczególnych części mózgu towarzyszy regionalny wzrost przepływu krwi i metabolizmu glukozy, przy czym oba stany są wzajemnie sprzężone, tj. regionalnemu wzrostowi metabolizmu glukozy prawie zawsze towarzyszy wzrost regionalnego przepływu krwi. Wyjątkiem są niektóre śpiączki i zatrucia. 
* Regionalny przepływ i metabolizm mózgowy definiują cztery badania neuroradiologiczne: SPECT, PET oraz funkcjonalne modyfikacje tomografii komputerowej i jądrowego rezonansu magnetycznego. 
* Ponadto, w mózgu istnieje masa różnych receptorów: dla dopaminy, serotoniny, opiatów etc. Ich gęstość ulega znaczącym zmianom w różnych stanach psychopatologicznych. 

##### **Weterynaryjna medycyna nuklearna**

* Zwierzęta chorują tak jak ludzie i diagnozowane są  tak jak ludzie, również radiologicznie
* Otępienia u zwierząt są dość powszechne, zwłaszcza u psów: pourazowo lub na tle dość powszechnej niedoczynności tarczycy; 
* Istnieje bateria testów psychologicznych, najbardziej znany jest test lustra: otępiały pies, widząc swoje odbicie w lustrze wraca do zachowań z okresu szczenięcego `cooooooooo`

##### **Metody badania**

* Podstawą wszystkich czterech metod jest tomografia, czyli trójwymiarowe obrazowanie mózgu z rekonstrukcją i oceną obrazu:  albo jako bryły, albo w cienkich przekrojach (warstwach) odzwierciedlających rozkład przepływu mózgowego krwi lub mózgowego metabolizmu glukozy. 
* Metody te oparte są albo na badaniu rozmieszczenia w mózgu („mapki”) radioizotopu technetu lub fluoru (PET, SPECT), albo: 
* Zmian przepływu mózgowego w badaniu radiologicznym: funkcjonalna tomografia komputerowa lub funkcjonalny rezonans magnetyczny – badanie perfuzji i dyfuzji w mózgu. 
* Z punktu widzenia neuropsychologii najistotniejsza jest metoda SPECT, PET orazczynnościowa odmiana jądrowego rezonansu magnetycznego (MRI): 
    + Umożliwiają one powtarzanie czynnościowej oceny mózgu powtarzanej w stosunkowo krótkim czasie;  posłużyły między innymi ocenie aktywacji układu nagrody u zakupoholików i seksoholików oraz w badaniach reakcji zagrożeń w psychologii wojskowej i w zespole stresu pourazowego   (PTSD). 
    

##### _**1. Tomografia komputerowa - TK**_
   + **Tomografia komputerowa** (nagroda Nobla dla Sir Godfrey Hounsfielda w roku 1979) jest tomograficzną metodą radiodiagnostyczną umożliwiającą ocenę cienkich przekrojów narządów miąższowych, w tym mózgu, na drodze synchronicznego ruchu lampy rentgenowskiej i detektora promieniowania wokół ciała badanego. 
    + Wprowadzenie tomografii komputerowej była jedną z trzech wielkich rewolucji technologicznych w diagnostyce obrazowej, porównywalnych do odkrycia promieni rentgenowskich. 
    + Tomografia komputerowa oparta jest na ciągłej rotacji wokół głowy badanego zespołu lampa-detektor. Jeżeli do tego dodamy osiowy ruch stołu badanego, umożliwia to zbadanie rozległych obszarów ciała ludzkiego (spiralna tomografia komputerowa). 
    + Szerokość badania TK zależy od liczby warstw badania organu (w tym mózgu). Ogólnie, do  badań mózgu wystarczą  aparaty sześcio- lub szesnastowarstwowe, aparaty wyższych generacji (40- lub 64 warstwowe znajdują raczej zastosowanie w radiologii kardiologicznej lub onkologicznej). 
    
* **Badanie perfuzji (przepływu krwi) TK:**
    + Największe znaczenie ma w świeżych udarach mózgu: przedstawia zmiany czynnościowe, w odróżnieniu od klasycznej tomografii komputerowej, która obrazuje zmiany morfologiczne, 
    + obrazuje zaburzenia ukrwienia grożące zawałem, 
jest czułym narzędziem diagnostycznym zwłaszcza dla rozpoznawania i prognozowania wczesnych udarów niedokrwiennych. 
    + polega na ocenie zmian gęstości tkankowej, zależnej od przepływu jodowego środka kontrastowego przez łożysko naczyniowe mózgowia, 
    + umożliwia pośrednią ocenę krążenia w dużych naczyniach, 
pozwala przewidywać następstwa udaru.





 




