---
title: "spot"
author: "Agata Zywert"
date: "1 kwietnia 2018"
output: html_document
---

`Czas - na maksie_ 2 m 45 sek_ nie wiecej (mogloby mniej)`


##### Poczπtek ok _15 sek_ - scena na zasadzie no spacer po uczelni i lepiej AGN i moøe CMI? na pewno nie tuwima
####LOGO PSYCHOLOGIA ZDROWIA
#### **Potem _30/40 sekund_ w tle wyblurowane (lub nie?) ujÍcia z zajÍÊ? chyba z zajeÊ ewentualnie np. jak gadamy sobie na korytarzu**

**Jakie zajÍcia by moøna wsadziÊ øeby nie wyglπda≥y zjebanie?**

* StatystykÍ z Tomkiem? - tylko ten tuwim boze
* Moze poudawaÊ anatomie w biblio CBMu? trzeba zalatwic morysia i mÛzgi
* Kompy z krzychem w CMI? tylko tam jest ciasno, ale to siÍ ogarnie
* Jakieú standardowe zajÍcia ale gdzie ludzie siÍ zg≥aszajπ i gadajπ - moøe seminarium z osobowoúci z dr B≥aøek
* Neuroradiologie bÍdziemy mieli w jakimú kozackim miejsu z maszynami? Jeúli tak to sztos jak chuj i tam trzeba krÍciÊ
* Co robiπ pierwszaki na Êwiczeniach ze spo≥ecznej? 

##### **DO TEGO INFO O:**
- jednolite studia magisterskie z psychologi **PIERWSZY RAZ NA UCZELNI MEDYCZNEJ**
- doúwiadczona kadra ktÛrπ tworzπ psychologie, Lekarze i inni ludzie xDDDD
- standardowy program nauczania wzbogacony o te biologiczne wypierdy (w tle wtedy moglaby byc anatomia lub neuroradiolololo)

`RAZEM TO MA BYC NIE WIECEJ NIZ MINUTA`

`i tyle` 

##### nastÍpne max _80/95 sekund_

* _20/30 sekund migawek_ z rzeczy, ktÛre robi ko≥o? ktÛre nic jeszcze nie robi xD ale coú by mog≥o to byÊ np. no nie wiem chuj wie, moøna
w to wsadziÊ np. UTW albo eksperyment zeby jakos wyglπda≥o. + Moøe coú øe robimy coú naukowego kurde badania jak normalni ludzie, ale jak to pokazaÊ?

       + moøna teø wsadziÊ z _10/15_ sekund migawek z drzwi otwartych jak coú nagram
      + tu moøna daÊ info, ze instnieje ko≥o naukowe
  
* 15/20 sekund Julii Kraszewskiej ktÛra mÛwi o tym czym jest ko≥o
* WYPOWIEDZI STUDENT”W - 2/3 (Ola Zamarja, moøe Paula Jarosz, Basia, Ada?) od nas i 2/3 z 1 klasy (ch≥opÛw jakiú koniecznie)
    + sugerowane pytania (co dla Ciebie oznacza studiowanie psychologii zdrowia - niech powiedzπ coú mπdrego i kaødy coú innego, np. øe mogπ rozwijaÊ swojπ pasjÍ i ≥πczyÊ
 rÛøne pasjÍ ze sobπ czy coú, øe mogπ siÍ rozwijaÊ teø pod kπtem medycznym, øe uczelnia dajÍ dostÍp to fajnych rzeczy i miejsc _**CO JEST WIERUTNYM K£AMSTWEM**_

##### **TO POWINNO TRWA∆ NIE WI CEJ NIØ _30/40_ sekund**- wiÍc wypowiedzi majπ mieÊ úrednio 5 sekund czyli jest wstÍp (napis? narrator? XD)

* **"Studiowanie psychologii zdrowia to dla mnie..."**
   
* i np. (5 sekund) "Szansa na zanudzenie siÍ na úmierÊ" `(powiedzenie tego zajmuje 3 sekundy)`

* WYPOWIEDZI WYK£ADOWC”W 4, max. 5 - nwm o co ich zapytaÊ, moøe jakby co ich zdaniem charakteryzuje studenta psych zdrowia albo no kurde nwm

  + _Emila?_ Niech Emila coú powie mπdrego i neurowego
  + _Syla?_ Niech coú powie NIEG£UPIEGO moøe coú szpitalnego i niech nie mÛwi øe _WY DZIEWCZYNY TO JESTEåCIE GWIAZDY_ 
  + _Majko!_ Majko niech powie coú cudownego, ale moøe mniej mamroczπco i niech siÍ lepiej streúci. Ale na pewno powie coú cool
  + _Krzych_ niech coú powie, ale niech siÍ postara siÍ wyglπdaÊ jak gbur 
  
#### **TO TEØ NIE POWINNO TRWA∆ WI CEJ NIØ 40 SEKUND** Niech jak bd ich 4 to ich wypowiedzi trwajπ 10 sekund 

* **"Dla mnie student psychologii zdrowia to cz≥owiek..."**

* "KtÛry powinien zabiÊ siÍ w przeciπgu nastÍpnych 3 lat, gdyø nie ma dla niego øadnej przysz≥oúci" `(6,65 sekund :))`
  
#### **WAØNE**: Nagrywki wypowiedzi najlepiej øeby by≥y nagrywane w CMI - jasno! ≥adne t≥o
   
  * TYLKO KWESTIA CO Z DèWI KIEM? Albo w jakiejú ograniczonej przestrzeni albo trzeba ogarnπÊ mikrofon
  
##### Ca≥oúÊ powinna siÍ zamknπc w tych 2.45 min ale to juø teø moje zadanie, øeby to tak poucinaÊ
  
#### PYTANIA, KT”RE MUSISZ ZADA∆ KOMUå KTO MA JAK•KOLWIEK W£ADZ 
  
  * Czy mogÍ nagrywaÊ wszystko bez praw autorskich do wlasnych mord
  * Czy mogÍ udawaÊ zajÍcia np z anatomii w CBM
  * kto z 1 klasy siÍ nadaje do gadania
  * Co ze sprzÍtem
  * jaki robimy dedlajn
 

